name: build-and-deploy

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push Web
        uses: docker/build-push-action@v2
        with:
          file: ./docker/development/Dockerfile
          context: .
          push: true
          tags: steemit/steemdb:development,steemit/steemdb:latest
      -
        name: Build and Push History
        uses: docker/build-push-action@v2
        with:
          file: ./docker/history/Dockerfile
          context: .
          push: true
          tags: steemit/steemdb:history
      -
        name: Build and Push Live
        uses: docker/build-push-action@v2
        with:
          file: ./docker/live/Dockerfile
          context: .
          push: true
          tags: steemit/steemdb:live
      -
        name: Build and Push Sync
        uses: docker/build-push-action@v2
        with:
          file: ./docker/sync/Dockerfile
          context: .
          push: true
          tags: steemit/steemdb:sync
      -
        name: Build and Push Witnesses
        uses: docker/build-push-action@v2
        with:
          file: ./docker/witnesses/Dockerfile
          context: .
          push: true
          tags: steemit/steemdb:witnesses
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
